on: push
name: Build Tezos Client
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build
      env:
        PATH: /root/.cargo/bin:$PATH
      run: |
        apt upgrade
        apt install rsync git m4 build-base patch unzip bubblewrap wget pkgconfig gmp-dev libev-dev hidapi-dev eudev-dev perl opam libusb-dev bash autoconf automake libtool linux-headers libffi-dev libgcc
        git clone --single-branch --branch v1.0.23 https://github.com/libusb/libusb.git --depth 1
        cd libusb && autoreconf -fvi && ./configure && make && make install
        git clone --single-branch --branch hidapi-0.9.0 https://github.com/libusb/hidapi.git --depth 1
        cd hidapi && autoreconf -fvi && ./bootstrap && ./configure && make && make install
        rm -rf libusb hidapi
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
        rustup set profile minimal
        rustup toolchain install 1.39.0
        rustup default 1.39.0
