on: push
name: Build Tezos Client
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build
      run: |
        docker build --tag tezos-client .
        docker cp tezos-client:/tezos/tezos-client .
    - name: automatic release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          tezos-client
